{application,trot,
             [{description,"A web micro-framework based on Plug and Cowboy.\n"},
              {modules,['Elixir.Mix.Tasks.Trot.Server','Elixir.Trot',
                        'Elixir.Trot.AuthCheck','Elixir.Trot.LiveReload',
                        'Elixir.Trot.NotFound','Elixir.Trot.Router',
                        'Elixir.Trot.Supervisor','Elixir.Trot.Template',
                        'Elixir.Trot.Template.EEx',
                        'Elixir.Trot.Template.Engine',
                        'Elixir.Trot.Template.HAML','Elixir.Trot.Versioning']},
              {registered,[]},
              {vsn,"0.6.0"},
              {applications,[kernel,stdlib,elixir,logger,plug,cowboy,
                             plug_heartbeat]},
              {mod,{'Elixir.Trot',[]}}]}.
